### ISSUE TITLE
IJ Ultimate Incompatibilities

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb-intellij-plugin#48]
Not sure why but the latest Ultimate EAP edition started barfing. Got an email from the marketplace today.

See also: https://github.com/varabyte/kobweb-intellij-plugin/actions/runs/9361767816/job/25769307761

Getting a bunch of `NoSuchClassError` errors like this:

> Method com.varabyte.kobweb.intellij.colors.KobwebColorProviderKt.evaluateArguments(Collection $this$evaluateArguments, int argCount, Function1 evaluatedValueMapper) : Mapped[] references an unresolved class org.jetbrains.kotlin.analysis.api.components.KtConstantEvaluationMode. This can lead to **NoSuchClassError** exception at runtime.

**Comment by Nxllpointer** [comment]
Did you test if it actually throws a NoSuchClassError?

**Comment by bitspittle** [comment]
Super busy for Droidcon, just created the bug, will take a look next week.
I don't know why only ultimate would break and not community, hoping it is
a fluke on their side.
